export const theme = {
  colors: {
    sidebar: "#0a1628",
    sidebarBorder: "#0f2744",
    sidebarTextActive: "#e2f4fd",
    sidebarTextInactive: "#7ea8cc",
    accent: "#0ea5e9",
    accentHover: "#0284c7",
    accentLight: "#f0f9ff",
    accentBorder: "#bae6fd",
    background: "#f8fafc",
    card: "#ffffff",
    border: "#e2e8f0",
    borderStrong: "#cbd5e1",
    textPrimary: "#0a1628",
    textSecondary: "#64748b",
    textMuted: "#94a3b8",
    textDisabled: "#cbd5e1",
    success: "#16a34a",
    successLight: "#f0fdf4",
    successBorder: "#bbf7d0",
    warning: "#f97316",
    warningLight: "#fff7ed",
    warningBorder: "#fed7aa",
    danger: "#dc2626",
    dangerLight: "#fef2f2",
    dangerBorder: "#fecaca",
    info: "#0ea5e9",
    infoLight: "#f0f9ff",
    infoBorder: "#bae6fd",
  },
  borderRadius: {
    sm: "7px",
    md: "10px",
    lg: "14px",
    xl: "20px",
  },
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    xxl: "48px",
  },
  fontSize: {
    xs: "11px",
    sm: "12px",
    base: "14px",
    md: "15px",
    lg: "18px",
    xl: "22px",
    xxl: "28px",
  },
} as const;